<template>
	<article>
		<div class="header">
			<div class="title">FONTICON AWESOME</div>
		</div>
		<div class="content">
			<div class="label label-info label-twins"><span>fa</span><span>主樣式</span></div>
			<div class="label label-info label-twins"><span>fa-*</span><span>使用方式</span></div>
			<div class="styleWrap">
				<IC :dataItem="this.icons"></IC>
			</div>
		</div>
	</article>
</template>
<script>
import IC from '@/views/components/iconCard'
export default {
	data(){
		return {
			icons:{
				"root": "fa",
			    "prefixed": "fa-",
			    "selection": [
					{"name": "500px", "l": "500px"},
					{"name": "adjust", "l": "Adjust"},
					{"name": "adn", "l": "Adn"},
					{"name": "align-center", "l": "Align center"},
					{"name": "align-justify", "l": "Align justify"},
					{"name": "align-left", "l": "Align left"},
					{"name": "align-right", "l": "Align right"},
					{"name": "amazon", "l": "Amazon"},
					{"name": "ambulance", "l": "Ambulance"},
					{"name": "anchor", "l": "Anchor"},
					{"name": "android", "l": "Android"},
					{"name": "angellist", "l": "Angellist"},
					{"name": "angle-double-down", "l": "Angle double down"},
					{"name": "angle-double-left", "l": "Angle double left"},
					{"name": "angle-double-right", "l": "Angle double right"},
					{"name": "angle-double-up", "l": "Angle double up"},
					{"name": "angle-down", "l": "Angle down"},
					{"name": "angle-left", "l": "Angle left"},
					{"name": "angle-right", "l": "Angle right"},
					{"name": "angle-up", "l": "Angle up"},
					{"name": "apple", "l": "Apple"},
					{"name": "archive", "l": "Archive"},
					{"name": "area-chart", "l": "Area chart"},
					{"name": "arrow-circle-down", "l": "Arrow circle down"},
					{"name": "arrow-circle-left", "l": "Arrow circle left"},
					{"name": "arrow-circle-o-down", "l": "Arrow circle o down"},
					{"name": "arrow-circle-o-left", "l": "Arrow circle o left"},
					{"name": "arrow-circle-o-right", "l": "Arrow circle o right"},
					{"name": "arrow-circle-o-up", "l": "Arrow circle o up"},
					{"name": "arrow-circle-right", "l": "Arrow circle right"},
					{"name": "arrow-circle-up", "l": "Arrow circle up"},
					{"name": "arrow-down", "l": "Arrow down"},
					{"name": "arrow-left", "l": "Arrow left"},
					{"name": "arrow-right", "l": "Arrow right"},
					{"name": "arrow-up", "l": "Arrow up"},
					{"name": "arrows", "l": "Arrows"},
					{"name": "arrows-alt", "l": "Arrows alt"},
					{"name": "arrows-h", "l": "Arrows h"},
					{"name": "arrows-v", "l": "Arrows v"},
					{"name": "asterisk", "l": "Asterisk"},
					{"name": "at", "l": "At"},
					{"name": "backward", "l": "Backward"},
					{"name": "balance-scale", "l": "Balance scale"},
					{"name": "ban", "l": "Ban"},
					{"name": "bar-chart", "l": "Bar chart"},
					{"name": "barcode", "l": "Barcode"},
					{"name": "bars", "l": "Bars"},
					{"name": "battery-empty", "l": "Battery empty"},
					{"name": "battery-full", "l": "Battery full"},
					{"name": "battery-half", "l": "Battery half"},
					{"name": "battery-quarter", "l": "Battery quarter"},
					{"name": "battery-three-quarters", "l": "Battery three quarters"},
					{"name": "bed", "l": "Bed"},
					{"name": "beer", "l": "Beer"},
					{"name": "behance", "l": "Behance"},
					{"name": "behance-square", "l": "Behance square"},
					{"name": "bell", "l": "Bell"},
					{"name": "bell-o", "l": "Bell o"},
					{"name": "bell-slash", "l": "Bell slash"},
					{"name": "bell-slash-o", "l": "Bell slash o"},
					{"name": "bicycle", "l": "Bicycle"},
					{"name": "binoculars", "l": "Binoculars"},
					{"name": "birthday-cake", "l": "Birthday cake"},
					{"name": "bitbucket", "l": "Bitbucket"},
					{"name": "bitbucket-square", "l": "Bitbucket square"},
					{"name": "black-tie", "l": "Black tie"},
					{"name": "bold", "l": "Bold"},
					{"name": "bolt", "l": "Bolt"},
					{"name": "bomb", "l": "Bomb"},
					{"name": "book", "l": "Book"},
					{"name": "bookmark", "l": "Bookmark"},
					{"name": "bookmark-o", "l": "Bookmark o"},
					{"name": "briefcase", "l": "Briefcase"},
					{"name": "btc", "l": "Btc"},
					{"name": "bug", "l": "Bug"},
					{"name": "building", "l": "Building"},
					{"name": "building-o", "l": "Building o"},
					{"name": "bullhorn", "l": "Bullhorn"},
					{"name": "bullseye", "l": "Bullseye"},
					{"name": "bus", "l": "Bus"},
					{"name": "buysellads", "l": "Buysellads"},
					{"name": "calculator", "l": "Calculator"},
					{"name": "calendar", "l": "Calendar"},
					{"name": "calendar-check-o", "l": "Calendar check o"},
					{"name": "calendar-minus-o", "l": "Calendar minus o"},
					{"name": "calendar-o", "l": "Calendar o"},
					{"name": "calendar-plus-o", "l": "Calendar plus o"},
					{"name": "calendar-times-o", "l": "Calendar times o"},
					{"name": "camera", "l": "Camera"},
					{"name": "camera-retro", "l": "Camera retro"},
					{"name": "car", "l": "Car"},
					{"name": "caret-down", "l": "Caret down"},
					{"name": "caret-left", "l": "Caret left"},
					{"name": "caret-right", "l": "Caret right"},
					{"name": "caret-square-o-down", "l": "Caret square o down"},
					{"name": "caret-square-o-left", "l": "Caret square o left"},
					{"name": "caret-square-o-right", "l": "Caret square o right"},
					{"name": "caret-square-o-up", "l": "Caret square o up"},
					{"name": "caret-up", "l": "Caret up"},
					{"name": "cart-arrow-down", "l": "Cart arrow down"},
					{"name": "cart-plus", "l": "Cart plus"},
					{"name": "cc", "l": "Cc"},
					{"name": "cc-amex", "l": "Cc amex"},
					{"name": "cc-diners-club", "l": "Cc diners club"},
					{"name": "cc-discover", "l": "Cc discover"},
					{"name": "cc-jcb", "l": "Cc jcb"},
					{"name": "cc-mastercard", "l": "Cc mastercard"},
					{"name": "cc-paypal", "l": "Cc paypal"},
					{"name": "cc-stripe", "l": "Cc stripe"},
					{"name": "cc-visa", "l": "Cc visa"},
					{"name": "certificate", "l": "Certificate"},
					{"name": "chain-broken", "l": "Chain broken"},
					{"name": "check", "l": "Check"},
					{"name": "check-circle", "l": "Check circle"},
					{"name": "check-circle-o", "l": "Check circle o"},
					{"name": "check-square", "l": "Check square"},
					{"name": "check-square-o", "l": "Check square o"},
					{"name": "chevron-circle-down", "l": "Chevron circle down"},
					{"name": "chevron-circle-left", "l": "Chevron circle left"},
					{"name": "chevron-circle-right", "l": "Chevron circle right"},
					{"name": "chevron-circle-up", "l": "Chevron circle up"},
					{"name": "chevron-down", "l": "Chevron down"},
					{"name": "chevron-left", "l": "Chevron left"},
					{"name": "chevron-right", "l": "Chevron right"},
					{"name": "chevron-up", "l": "Chevron up"},
					{"name": "child", "l": "Child"},
					{"name": "chrome", "l": "Chrome"},
					{"name": "circle", "l": "Circle"},
					{"name": "circle-o", "l": "Circle o"},
					{"name": "circle-o-notch", "l": "Circle o notch"},
					{"name": "circle-thin", "l": "Circle thin"},
					{"name": "clipboard", "l": "Clipboard"},
					{"name": "clock-o", "l": "Clock o"},
					{"name": "clone", "l": "Clone"},
					{"name": "cloud", "l": "Cloud"},
					{"name": "cloud-download", "l": "Cloud download"},
					{"name": "cloud-upload", "l": "Cloud upload"},
					{"name": "code", "l": "Code"},
					{"name": "code-fork", "l": "Code fork"},
					{"name": "codepen", "l": "Codepen"},
					{"name": "coffee", "l": "Coffee"},
					{"name": "cog", "l": "Cog"},
					{"name": "cogs", "l": "Cogs"},
					{"name": "columns", "l": "Columns"},
					{"name": "comment", "l": "Comment"},
					{"name": "comment-o", "l": "Comment o"},
					{"name": "commenting", "l": "Commenting"},
					{"name": "commenting-o", "l": "Commenting o"},
					{"name": "comments", "l": "Comments"},
					{"name": "comments-o", "l": "Comments o"},
					{"name": "compass", "l": "Compass"},
					{"name": "compress", "l": "Compress"},
					{"name": "connectdevelop", "l": "Connectdevelop"},
					{"name": "contao", "l": "Contao"},
					{"name": "copyright", "l": "Copyright"},
					{"name": "creative-commons", "l": "Creative commons"},
					{"name": "credit-card", "l": "Credit card"},
					{"name": "crop", "l": "Crop"},
					{"name": "crosshairs", "l": "Crosshairs"},
					{"name": "css3", "l": "Css3"},
					{"name": "cube", "l": "Cube"},
					{"name": "cubes", "l": "Cubes"},
					{"name": "cutlery", "l": "Cutlery"},
					{"name": "dashcube", "l": "Dashcube"},
					{"name": "database", "l": "Database"},
					{"name": "delicious", "l": "Delicious"},
					{"name": "desktop", "l": "Desktop"},
					{"name": "deviantart", "l": "Deviantart"},
					{"name": "diamond", "l": "Diamond"},
					{"name": "digg", "l": "Digg"},
					{"name": "dot-circle-o", "l": "Dot circle o"},
					{"name": "download", "l": "Download"},
					{"name": "dribbble", "l": "Dribbble"},
					{"name": "dropbox", "l": "Dropbox"},
					{"name": "drupal", "l": "Drupal"},
					{"name": "eject", "l": "Eject"},
					{"name": "ellipsis-h", "l": "Ellipsis h"},
					{"name": "ellipsis-v", "l": "Ellipsis v"},
					{"name": "empire", "l": "Empire"},
					{"name": "envelope", "l": "Envelope"},
					{"name": "envelope-o", "l": "Envelope o"},
					{"name": "envelope-square", "l": "Envelope square"},
					{"name": "eraser", "l": "Eraser"},
					{"name": "eur", "l": "Eur"},
					{"name": "exchange", "l": "Exchange"},
					{"name": "exclamation", "l": "Exclamation"},
					{"name": "exclamation-circle", "l": "Exclamation circle"},
					{"name": "exclamation-triangle", "l": "Exclamation triangle"},
					{"name": "expand", "l": "Expand"},
					{"name": "expeditedssl", "l": "Expeditedssl"},
					{"name": "external-link", "l": "External link"},
					{"name": "external-link-square", "l": "External link square"},
					{"name": "eye", "l": "Eye"},
					{"name": "eye-slash", "l": "Eye slash"},
					{"name": "eyedropper", "l": "Eyedropper"},
					{"name": "facebook", "l": "Facebook"},
					{"name": "facebook-official", "l": "Facebook official"},
					{"name": "facebook-square", "l": "Facebook square"},
					{"name": "fast-backward", "l": "Fast backward"},
					{"name": "fast-forward", "l": "Fast forward"},
					{"name": "fax", "l": "Fax"},
					{"name": "female", "l": "Female"},
					{"name": "fighter-jet", "l": "Fighter jet"},
					{"name": "file", "l": "File"},
					{"name": "file-archive-o", "l": "File archive o"},
					{"name": "file-audio-o", "l": "File audio o"},
					{"name": "file-code-o", "l": "File code o"},
					{"name": "file-excel-o", "l": "File excel o"},
					{"name": "file-image-o", "l": "File image o"},
					{"name": "file-o", "l": "File o"},
					{"name": "file-pdf-o", "l": "File pdf o"},
					{"name": "file-powerpoint-o", "l": "File powerpoint o"},
					{"name": "file-text", "l": "File text"},
					{"name": "file-text-o", "l": "File text o"},
					{"name": "file-video-o", "l": "File video o"},
					{"name": "file-word-o", "l": "File word o"},
					{"name": "files-o", "l": "Files o"},
					{"name": "film", "l": "Film"},
					{"name": "filter", "l": "Filter"},
					{"name": "fire", "l": "Fire"},
					{"name": "fire-extinguisher", "l": "Fire extinguisher"},
					{"name": "firefox", "l": "Firefox"},
					{"name": "flag", "l": "Flag"},
					{"name": "flag-checkered", "l": "Flag checkered"},
					{"name": "flag-o", "l": "Flag o"},
					{"name": "flask", "l": "Flask"},
					{"name": "flickr", "l": "Flickr"},
					{"name": "floppy-o", "l": "Floppy o"},
					{"name": "folder", "l": "Folder"},
					{"name": "folder-o", "l": "Folder o"},
					{"name": "folder-open", "l": "Folder open"},
					{"name": "folder-open-o", "l": "Folder open o"},
					{"name": "font", "l": "Font"},
					{"name": "fonticons", "l": "Fonticons"},
					{"name": "forumbee", "l": "Forumbee"},
					{"name": "forward", "l": "Forward"},
					{"name": "foursquare", "l": "Foursquare"},
					{"name": "frown-o", "l": "Frown o"},
					{"name": "futbol-o", "l": "Futbol o"},
					{"name": "gamepad", "l": "Gamepad"},
					{"name": "gavel", "l": "Gavel"},
					{"name": "gbp", "l": "Gbp"},
					{"name": "genderless", "l": "Genderless"},
					{"name": "get-pocket", "l": "Get pocket"},
					{"name": "gg", "l": "Gg"},
					{"name": "gg-circle", "l": "Gg circle"},
					{"name": "gift", "l": "Gift"},
					{"name": "git", "l": "Git"},
					{"name": "git-square", "l": "Git square"},
					{"name": "github", "l": "Github"},
					{"name": "github-alt", "l": "Github alt"},
					{"name": "github-square", "l": "Github square"},
					{"name": "glass", "l": "Glass"},
					{"name": "globe", "l": "Globe"},
					{"name": "google", "l": "Google"},
					{"name": "google-plus", "l": "Google plus"},
					{"name": "google-plus-square", "l": "Google plus square"},
					{"name": "google-wallet", "l": "Google wallet"},
					{"name": "graduation-cap", "l": "Graduation cap"},
					{"name": "gratipay", "l": "Gratipay"},
					{"name": "h-square", "l": "H square"},
					{"name": "hacker-news", "l": "Hacker news"},
					{"name": "hand-lizard-o", "l": "Hand lizard o"},
					{"name": "hand-o-down", "l": "Hand o down"},
					{"name": "hand-o-left", "l": "Hand o left"},
					{"name": "hand-o-right", "l": "Hand o right"},
					{"name": "hand-o-up", "l": "Hand o up"},
					{"name": "hand-paper-o", "l": "Hand paper o"},
					{"name": "hand-peace-o", "l": "Hand peace o"},
					{"name": "hand-pointer-o", "l": "Hand pointer o"},
					{"name": "hand-rock-o", "l": "Hand rock o"},
					{"name": "hand-scissors-o", "l": "Hand scissors o"},
					{"name": "hand-spock-o", "l": "Hand spock o"},
					{"name": "hdd-o", "l": "Hdd o"},
					{"name": "header", "l": "Header"},
					{"name": "headphones", "l": "Headphones"},
					{"name": "heart", "l": "Heart"},
					{"name": "heart-o", "l": "Heart o"},
					{"name": "heartbeat", "l": "Heartbeat"},
					{"name": "history", "l": "History"},
					{"name": "home", "l": "Home"},
					{"name": "hospital-o", "l": "Hospital o"},
					{"name": "hourglass", "l": "Hourglass"},
					{"name": "hourglass-end", "l": "Hourglass end"},
					{"name": "hourglass-half", "l": "Hourglass half"},
					{"name": "hourglass-o", "l": "Hourglass o"},
					{"name": "hourglass-start", "l": "Hourglass start"},
					{"name": "houzz", "l": "Houzz"},
					{"name": "html5", "l": "Html5"},
					{"name": "i-cursor", "l": "I cursor"},
					{"name": "ils", "l": "Ils"},
					{"name": "inbox", "l": "Inbox"},
					{"name": "indent", "l": "Indent"},
					{"name": "industry", "l": "Industry"},
					{"name": "info", "l": "Info"},
					{"name": "info-circle", "l": "Info circle"},
					{"name": "inr", "l": "Inr"},
					{"name": "instagram", "l": "Instagram"},
					{"name": "internet-explorer", "l": "Internet explorer"},
					{"name": "ioxhost", "l": "Ioxhost"},
					{"name": "italic", "l": "Italic"},
					{"name": "joomla", "l": "Joomla"},
					{"name": "jpy", "l": "Jpy"},
					{"name": "jsfiddle", "l": "Jsfiddle"},
					{"name": "key", "l": "Key"},
					{"name": "keyboard-o", "l": "Keyboard o"},
					{"name": "krw", "l": "Krw"},
					{"name": "language", "l": "Language"},
					{"name": "laptop", "l": "Laptop"},
					{"name": "lastfm", "l": "Lastfm"},
					{"name": "lastfm-square", "l": "Lastfm square"},
					{"name": "leaf", "l": "Leaf"},
					{"name": "leanpub", "l": "Leanpub"},
					{"name": "lemon-o", "l": "Lemon o"},
					{"name": "level-down", "l": "Level down"},
					{"name": "level-up", "l": "Level up"},
					{"name": "life-ring", "l": "Life ring"},
					{"name": "lightbulb-o", "l": "Lightbulb o"},
					{"name": "line-chart", "l": "Line chart"},
					{"name": "link", "l": "Link"},
					{"name": "linkedin", "l": "Linkedin"},
					{"name": "linkedin-square", "l": "Linkedin square"},
					{"name": "linux", "l": "Linux"},
					{"name": "list", "l": "List"},
					{"name": "list-alt", "l": "List alt"},
					{"name": "list-ol", "l": "List ol"},
					{"name": "list-ul", "l": "List ul"},
					{"name": "location-arrow", "l": "Location arrow"},
					{"name": "lock", "l": "Lock"},
					{"name": "long-arrow-down", "l": "Long arrow down"},
					{"name": "long-arrow-left", "l": "Long arrow left"},
					{"name": "long-arrow-right", "l": "Long arrow right"},
					{"name": "long-arrow-up", "l": "Long arrow up"},
					{"name": "magic", "l": "Magic"},
					{"name": "magnet", "l": "Magnet"},
					{"name": "male", "l": "Male"},
					{"name": "map", "l": "Map"},
					{"name": "map-marker", "l": "Map marker"},
					{"name": "map-o", "l": "Map o"},
					{"name": "map-pin", "l": "Map pin"},
					{"name": "map-signs", "l": "Map signs"},
					{"name": "mars", "l": "Mars"},
					{"name": "mars-double", "l": "Mars double"},
					{"name": "mars-stroke", "l": "Mars stroke"},
					{"name": "mars-stroke-h", "l": "Mars stroke h"},
					{"name": "mars-stroke-v", "l": "Mars stroke v"},
					{"name": "maxcdn", "l": "Maxcdn"},
					{"name": "meanpath", "l": "Meanpath"},
					{"name": "medium", "l": "Medium"},
					{"name": "medkit", "l": "Medkit"},
					{"name": "meh-o", "l": "Meh o"},
					{"name": "mercury", "l": "Mercury"},
					{"name": "microphone", "l": "Microphone"},
					{"name": "microphone-slash", "l": "Microphone slash"},
					{"name": "minus", "l": "Minus"},
					{"name": "minus-circle", "l": "Minus circle"},
					{"name": "minus-square", "l": "Minus square"},
					{"name": "minus-square-o", "l": "Minus square o"},
					{"name": "mobile", "l": "Mobile"},
					{"name": "money", "l": "Money"},
					{"name": "moon-o", "l": "Moon o"},
					{"name": "motorcycle", "l": "Motorcycle"},
					{"name": "mouse-pointer", "l": "Mouse pointer"},
					{"name": "music", "l": "Music"},
					{"name": "neuter", "l": "Neuter"},
					{"name": "newspaper-o", "l": "Newspaper o"},
					{"name": "object-group", "l": "Object group"},
					{"name": "object-ungroup", "l": "Object ungroup"},
					{"name": "odnoklassniki", "l": "Odnoklassniki"},
					{"name": "odnoklassniki-square", "l": "Odnoklassniki square"},
					{"name": "opencart", "l": "Opencart"},
					{"name": "openid", "l": "Openid"},
					{"name": "opera", "l": "Opera"},
					{"name": "optin-monster", "l": "Optin monster"},
					{"name": "outdent", "l": "Outdent"},
					{"name": "pagelines", "l": "Pagelines"},
					{"name": "paint-brush", "l": "Paint brush"},
					{"name": "paper-plane", "l": "Paper plane"},
					{"name": "paper-plane-o", "l": "Paper plane o"},
					{"name": "paperclip", "l": "Paperclip"},
					{"name": "paragraph", "l": "Paragraph"},
					{"name": "pause", "l": "Pause"},
					{"name": "paw", "l": "Paw"},
					{"name": "paypal", "l": "Paypal"},
					{"name": "pencil", "l": "Pencil"},
					{"name": "pencil-square", "l": "Pencil square"},
					{"name": "pencil-square-o", "l": "Pencil square o"},
					{"name": "phone", "l": "Phone"},
					{"name": "phone-square", "l": "Phone square"},
					{"name": "picture-o", "l": "Picture o"},
					{"name": "pie-chart", "l": "Pie chart"},
					{"name": "pied-piper", "l": "Pied piper"},
					{"name": "pied-piper-alt", "l": "Pied piper alt"},
					{"name": "pinterest", "l": "Pinterest"},
					{"name": "pinterest-p", "l": "Pinterest p"},
					{"name": "pinterest-square", "l": "Pinterest square"},
					{"name": "plane", "l": "Plane"},
					{"name": "play", "l": "Play"},
					{"name": "play-circle", "l": "Play circle"},
					{"name": "play-circle-o", "l": "Play circle o"},
					{"name": "plug", "l": "Plug"},
					{"name": "plus", "l": "Plus"},
					{"name": "plus-circle", "l": "Plus circle"},
					{"name": "plus-square", "l": "Plus square"},
					{"name": "plus-square-o", "l": "Plus square o"},
					{"name": "power-off", "l": "Power off"},
					{"name": "print", "l": "Print"},
					{"name": "puzzle-piece", "l": "Puzzle piece"},
					{"name": "qq", "l": "Qq"},
					{"name": "qrcode", "l": "Qrcode"},
					{"name": "question", "l": "Question"},
					{"name": "question-circle", "l": "Question circle"},
					{"name": "quote-left", "l": "Quote left"},
					{"name": "quote-right", "l": "Quote right"},
					{"name": "random", "l": "Random"},
					{"name": "rebel", "l": "Rebel"},
					{"name": "recycle", "l": "Recycle"},
					{"name": "reddit", "l": "Reddit"},
					{"name": "reddit-square", "l": "Reddit square"},
					{"name": "refresh", "l": "Refresh"},
					{"name": "registered", "l": "Registered"},
					{"name": "renren", "l": "Renren"},
					{"name": "repeat", "l": "Repeat"},
					{"name": "reply", "l": "Reply"},
					{"name": "reply-all", "l": "Reply all"},
					{"name": "retweet", "l": "Retweet"},
					{"name": "road", "l": "Road"},
					{"name": "rocket", "l": "Rocket"},
					{"name": "rss", "l": "Rss"},
					{"name": "rss-square", "l": "Rss square"},
					{"name": "rub", "l": "Rub"},
					{"name": "safari", "l": "Safari"},
					{"name": "scissors", "l": "Scissors"},
					{"name": "search", "l": "Search"},
					{"name": "search-minus", "l": "Search minus"},
					{"name": "search-plus", "l": "Search plus"},
					{"name": "sellsy", "l": "Sellsy"},
					{"name": "server", "l": "Server"},
					{"name": "share", "l": "Share"},
					{"name": "share-alt", "l": "Share alt"},
					{"name": "share-alt-square", "l": "Share alt square"},
					{"name": "share-square", "l": "Share square"},
					{"name": "share-square-o", "l": "Share square o"},
					{"name": "shield", "l": "Shield"},
					{"name": "ship", "l": "Ship"},
					{"name": "shirtsinbulk", "l": "Shirtsinbulk"},
					{"name": "shopping-cart", "l": "Shopping cart"},
					{"name": "sign-in", "l": "Sign in"},
					{"name": "sign-out", "l": "Sign out"},
					{"name": "signal", "l": "Signal"},
					{"name": "simplybuilt", "l": "Simplybuilt"},
					{"name": "sitemap", "l": "Sitemap"},
					{"name": "skyatlas", "l": "Skyatlas"},
					{"name": "skype", "l": "Skype"},
					{"name": "slack", "l": "Slack"},
					{"name": "sliders", "l": "Sliders"},
					{"name": "slideshare", "l": "Slideshare"},
					{"name": "smile-o", "l": "Smile o"},
					{"name": "sort", "l": "Sort"},
					{"name": "sort-alpha-asc", "l": "Sort alpha asc"},
					{"name": "sort-alpha-desc", "l": "Sort alpha desc"},
					{"name": "sort-amount-asc", "l": "Sort amount asc"},
					{"name": "sort-amount-desc", "l": "Sort amount desc"},
					{"name": "sort-asc", "l": "Sort asc"},
					{"name": "sort-desc", "l": "Sort desc"},
					{"name": "sort-numeric-asc", "l": "Sort numeric asc"},
					{"name": "sort-numeric-desc", "l": "Sort numeric desc"},
					{"name": "soundcloud", "l": "Soundcloud"},
					{"name": "space-shuttle", "l": "Space shuttle"},
					{"name": "spinner", "l": "Spinner"},
					{"name": "spoon", "l": "Spoon"},
					{"name": "spotify", "l": "Spotify"},
					{"name": "square", "l": "Square"},
					{"name": "square-o", "l": "Square o"},
					{"name": "stack-exchange", "l": "Stack exchange"},
					{"name": "stack-overflow", "l": "Stack overflow"},
					{"name": "star", "l": "Star"},
					{"name": "star-half", "l": "Star half"},
					{"name": "star-half-o", "l": "Star half o"},
					{"name": "star-o", "l": "Star o"},
					{"name": "steam", "l": "Steam"},
					{"name": "steam-square", "l": "Steam square"},
					{"name": "step-backward", "l": "Step backward"},
					{"name": "step-forward", "l": "Step forward"},
					{"name": "stethoscope", "l": "Stethoscope"},
					{"name": "sticky-note", "l": "Sticky note"},
					{"name": "sticky-note-o", "l": "Sticky note o"},
					{"name": "stop", "l": "Stop"},
					{"name": "street-view", "l": "Street view"},
					{"name": "strikethrough", "l": "Strikethrough"},
					{"name": "stumbleupon", "l": "Stumbleupon"},
					{"name": "stumbleupon-circle", "l": "Stumbleupon circle"},
					{"name": "subscript", "l": "Subscript"},
					{"name": "subway", "l": "Subway"},
					{"name": "suitcase", "l": "Suitcase"},
					{"name": "sun-o", "l": "Sun o"},
					{"name": "superscript", "l": "Superscript"},
					{"name": "table", "l": "Table"},
					{"name": "tablet", "l": "Tablet"},
					{"name": "tachometer", "l": "Tachometer"},
					{"name": "tag", "l": "Tag"},
					{"name": "tags", "l": "Tags"},
					{"name": "tasks", "l": "Tasks"},
					{"name": "taxi", "l": "Taxi"},
					{"name": "television", "l": "Television"},
					{"name": "tencent-weibo", "l": "Tencent weibo"},
					{"name": "terminal", "l": "Terminal"},
					{"name": "text-height", "l": "Text height"},
					{"name": "text-width", "l": "Text width"},
					{"name": "th", "l": "Th"},
					{"name": "th-large", "l": "Th large"},
					{"name": "th-list", "l": "Th list"},
					{"name": "thumb-tack", "l": "Thumb tack"},
					{"name": "thumbs-down", "l": "Thumbs down"},
					{"name": "thumbs-o-down", "l": "Thumbs o down"},
					{"name": "thumbs-o-up", "l": "Thumbs o up"},
					{"name": "thumbs-up", "l": "Thumbs up"},
					{"name": "ticket", "l": "Ticket"},
					{"name": "times", "l": "Times"},
					{"name": "times-circle", "l": "Times circle"},
					{"name": "times-circle-o", "l": "Times circle o"},
					{"name": "tint", "l": "Tint"},
					{"name": "toggle-off", "l": "Toggle off"},
					{"name": "toggle-on", "l": "Toggle on"},
					{"name": "trademark", "l": "Trademark"},
					{"name": "train", "l": "Train"},
					{"name": "transgender", "l": "Transgender"},
					{"name": "transgender-alt", "l": "Transgender alt"},
					{"name": "trash", "l": "Trash"},
					{"name": "trash-o", "l": "Trash o"},
					{"name": "tree", "l": "Tree"},
					{"name": "trello", "l": "Trello"},
					{"name": "tripadvisor", "l": "Tripadvisor"},
					{"name": "trophy", "l": "Trophy"},
					{"name": "truck", "l": "Truck"},
					{"name": "try", "l": "Try"},
					{"name": "tty", "l": "Tty"},
					{"name": "tumblr", "l": "Tumblr"},
					{"name": "tumblr-square", "l": "Tumblr square"},
					{"name": "twitch", "l": "Twitch"},
					{"name": "twitter", "l": "Twitter"},
					{"name": "twitter-square", "l": "Twitter square"},
					{"name": "umbrella", "l": "Umbrella"},
					{"name": "underline", "l": "Underline"},
					{"name": "undo", "l": "Undo"},
					{"name": "university", "l": "University"},
					{"name": "unlock", "l": "Unlock"},
					{"name": "unlock-alt", "l": "Unlock alt"},
					{"name": "upload", "l": "Upload"},
					{"name": "usd", "l": "Usd"},
					{"name": "user", "l": "User"},
					{"name": "user-md", "l": "User md"},
					{"name": "user-plus", "l": "User plus"},
					{"name": "user-secret", "l": "User secret"},
					{"name": "user-times", "l": "User times"},
					{"name": "users", "l": "Users"},
					{"name": "venus", "l": "Venus"},
					{"name": "venus-double", "l": "Venus double"},
					{"name": "venus-mars", "l": "Venus mars"},
					{"name": "viacoin", "l": "Viacoin"},
					{"name": "video-camera", "l": "Video camera"},
					{"name": "vimeo", "l": "Vimeo"},
					{"name": "vimeo-square", "l": "Vimeo square"},
					{"name": "vine", "l": "Vine"},
					{"name": "vk", "l": "Vk"},
					{"name": "volume-down", "l": "Volume down"},
					{"name": "volume-off", "l": "Volume off"},
					{"name": "volume-up", "l": "Volume up"},
					{"name": "weibo", "l": "Weibo"},
					{"name": "weixin", "l": "Weixin"},
					{"name": "whatsapp", "l": "Whatsapp"},
					{"name": "wheelchair", "l": "Wheelchair"},
					{"name": "wifi", "l": "Wifi"},
					{"name": "wikipedia-w", "l": "Wikipedia w"},
					{"name": "windows", "l": "Windows"},
					{"name": "wordpress", "l": "Wordpress"},
					{"name": "wrench", "l": "Wrench"},
					{"name": "xing", "l": "Xing"},
					{"name": "xing-square", "l": "Xing square"},
					{"name": "y-combinator", "l": "Y combinator"},
					{"name": "yahoo", "l": "Yahoo"},
					{"name": "yelp", "l": "Yelp"},
					{"name": "youtube", "l": "Youtube"},
					{"name": "youtube-play", "l": "Youtube play"},
					{"name": "youtube-square", "l": "Youtube square"}
				]
			}
		};
	},
	components:{
		IC
	}
}
</script>